# Generated by Django 5.2.17 on 2026-09-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_organization_alter_experience_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='experience_thumbnails/'),
        ),
    ]
