# Generated by Django 5.2.17 on 2026-09-20 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_experience_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('uiux', 'UI/UX Design'), ('design', 'Design Branding'), ('other', 'Other')], default='web', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_thumbnails/')),
                ('project_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
